{% set name = "osyris" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/osyris-{{ version }}.tar.gz
  sha256: d61353f29f18ceaf14775de74b2477a7b03387c0e55409ad9dab207148d3497a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - matplotlib-base
    - numba
    - numpy
    - pint

test:
  imports:
    - osyris
  commands:
    - pip check
  requires:
    - pip
    - setuptools <60

about:
  home: https://github.com/osyris-project/osyris
  summary: A package to visualize AMR data from the RAMSES code
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nvaytet
