{% set name = "osyris" %}
{% set version = "2.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/osyris-{{ version }}.tar.gz
  sha256: cb06697084be5d11fd92a888023cc68f6c65e1b160495aefce23784f54954bc1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - matplotlib-base
    - numba
    - numpy
    - pint

test:
  imports:
    - osyris
  commands:
    - pip check
  requires:
    - pip
    - setuptools <60

about:
  home: https://github.com/osyris-project/osyris
  summary: A package to visualize AMR data from the RAMSES code
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nvaytet
