{% set name = "osyris" %}
{% set version = "2.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/osyris-{{ version }}.tar.gz
  sha256: dcaa7369c38cbe8ba99482d7e19d19d40c81c8e48987e8daf8035a192f57a491

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - matplotlib-base
    - numba
    - numpy
    - pint

test:
  imports:
    - osyris
  commands:
    - pip check
  requires:
    - pip
    - setuptools <60

about:
  home: https://github.com/osyris-project/osyris
  summary: A package to visualize AMR data from the RAMSES code
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nvaytet
